yarnPath: .yarn/releases/yarn-3.1.1.cjs

# We are not using PnP now due to the incompatibility with gatsby-plugin-page-creator, see https://github.com/gatsbyjs/gatsby/discussions/20949#discussioncomment-1246187
nodeLinker: node-modules
